<?php

$_ENV['PLATFORM_APP_DIR'] = getenv('PLATFORM_APP_DIR');
$_ENV['PLATFORM_APPLICATION'] = getenv('PLATFORM_APPLICATION');
$_ENV['PLATFORM_APPLICATION_NAME'] = getenv('PLATFORM_APPLICATION_NAME');
$_ENV['PLATFORM_BRANCH'] = getenv('PLATFORM_BRANCH');
$_ENV['PLATFORM_DOCUMENT_ROOT'] = getenv('PLATFORM_DOCUMENT_ROOT');
$_ENV['PLATFORM_ENVIRONMENT'] = getenv('PLATFORM_ENVIRONMENT');
$_ENV['PLATFORM_PROJECT'] = getenv('PLATFORM_PROJECT');
$_ENV['PLATFORM_RELATIONSHIPS'] = getenv('PLATFORM_RELATIONSHIPS');
$_ENV['PLATFORM_ROUTES'] = getenv('PLATFORM_ROUTES');
$_ENV['PLATFORM_TREE_ID'] = getenv('PLATFORM_TREE_ID');
$_ENV['PLATFORM_VARIABLES'] = getenv('PLATFORM_VARIABLES');
$_ENV['PLATFORM_PROJECT_ENTROPY'] = getenv('PLATFORM_PROJECT_ENTROPY');
